Allow Suite To be Set via Accessor
evanphx/benchmark-ips pull request #113
Opened 2021-03-17 22:04 UTC by allcentury

This aims to close #112.

I removed references to `Benchmark::Suite` - I couldn't find anywhere
this was used and the original commit goes back a long ways.  This looks
like a relic to a class or module that I'm not able to find in git
history via

```
git grep 'Suite' $(git rev-list --all)
```

All config gets passed into `job.config job_opts` and now the block is
evaluated last allowing overrides.

2021-03-19 23:17 UTC, kbrock approved these changes
this looks nice.

not a fan of the `set_reporter` method but the removal of the if statements sure makes this nicer.

2021-03-19 23:17 UTC, kbrock commented on lib/benchmark/ips/job.rb
> +        self.quiet = opts[:quiet]
do you want to put an `if opts[:quiet]` guard clause here and with `:suite`?

2021-03-19 23:17 UTC, kbrock commented on lib/benchmark/ips/job.rb
> +        end
is it possible to simplify this?
```suggestion
        @suite = suite || Benchmark::IPS::NoopSuite.new
```

2021-03-19 23:17 UTC, kbrock commented on lib/benchmark/ips/job.rb
> +          @stdout.start_warming
thanks - this is much nicer

2021-03-19 23:17 UTC, kbrock commented on lib/benchmark/ips/job.rb
> +      def set_reporter(quiet:)
since this only accepts quiet, does it make sense to just move the contents of this over to `def quiet=`

or do you have plans on allowing a report to be passed into here in the future?
If you wanted that, you could do `quiet=true` or `reporter=NoopReport.new`

2021-03-19 23:17 UTC, kbrock commented on lib/benchmark/ips/job.rb
> +      attr_reader :quiet
does this need to be stored? does it make sense just comparing with noop class?
Is reading `quiet` even used / is it necessary?

2021-03-22 17:59 UTC, allcentury reviewed
Thanks for the review @kbrock !

2021-03-22 17:59 UTC, allcentury commented on lib/benchmark/ips/job.rb
> +      attr_reader :quiet
I have a generalist point of view that any state that can be publicly set should be get-able.  `quiet` is part of the public API in a few ways:

```ruby
Benchmark.ips(quiet: true) { }
```

or 

```ruby
Benchmark.ips do |x|
  x.quiet = true
end
```

2021-03-22 17:59 UTC, allcentury commented on lib/benchmark/ips/job.rb
> +        self.quiet = opts[:quiet]
I've pushed the conditional to `quiet=` at this time so no.

2021-03-22 17:59 UTC, allcentury commented on lib/benchmark/ips/job.rb
> +        end
I like this - thanks!

2021-03-22 17:59 UTC, allcentury commented on lib/benchmark/ips/job.rb
> +      def set_reporter(quiet:)
Great points.  I was thinking `reporter` should eventually use dependency injection and if no report is passed in then we'll default to `Noop`.  Then, we can actually decommission `quiet` from the public API and instead, if you don't want output you pass in the `NoopReport`.  I think the idea of a `reporter` and `quiet` are conflating the same thing but getting rid of `quiet` seemed like a breaking change at this time.

2021-03-22 18:03 UTC, allcentury commented on lib/benchmark/ips/job.rb
> +      def set_reporter(quiet:)
Maybe the answer is to have a public `reporter=` method that `self.quiet` calls and eventually we can deprecate it?  thoughts on that?

2021-03-22 23:06 UTC, kbrock reviewed
This is looking nice.
I like where you are going with `reporter=`

But please note, that while I have contributed a few PRs here, I am not the maintainer so take my words with a grain of salt.

I have put in a few PRs around better capturing the output, that is why I'm vocal here. A number of people have expressed the desire to have better output / hence another pr that I have open. this seems to overlap that one a bit - so keep it coming and I'll refactor that one.

2021-03-22 23:06 UTC, kbrock commented on lib/benchmark/ips/job.rb
> +      def set_reporter(quiet:)
I like that idea a lot. it is consistent with your current approach and the approach this project seems to be headed.
At one time, quiet made sense. But now that people want more control over capturing the output, introducing a reporter accessor sounds good.

2021-03-22 23:06 UTC, kbrock commented on lib/benchmark/ips/job.rb
> +        self.quiet = opts[:quiet]
I was worried that this would overwrite values, but since this is in the initializer, we actually very much do not want the conditional guard clause here. b/c we always want to set this to one of the 2 reporters.

2021-03-31 14:05 UTC, nateberkopec commented
Hey @allcentury - do you have more to add here or are you waiting on my input?

2021-03-31 20:54 UTC, allcentury commented
@kbrock - yes, I follow the [`fixup`](https://thoughtbot.com/blog/autosquashing-git-commits) flow until it's ready to merge, then I squash.  

@nateberkopec - thanks!  Ya, could use your input:

option A:

1. deprecate `quiet` in favor of setting a `reporter`.  
2. If you want no output, use the `NoopReporter`.  
3. Replace docs on `quiet` with `NoopReporter`
4. Eventually let anyone inject their own `Reporter` as long as it confirms to the [interface](https://github.com/evanphx/benchmark-ips/blob/master/lib/benchmark/ips/job/stdout_report.rb)
5. Do we merge format + reporter?  `CsvReporter`, `JsonReporter`, etc. 

option B:

1. Keep `quiet` and don't surface the `reporter` idea
2. Nothing to deprecate/change
3. Don't merge format config with the output config

Initially I thought `reporter` could allow users to write their own formatters like `csv`, `json`, etc.  However I see there is a [format option](https://github.com/evanphx/benchmark-ips/blob/5f9a28420688fb6c909af31d950724ab496f1bf2/lib/benchmark/ips.rb#L84-L90).  As it stands w/ this PR:

`StdoutReport`:

1.  Sends everything to stdout 

`NoopReport`:

1. No output

`:format` 

1. Raw or Human, used by the Report classes above.

Can you think of a good reason to have users inject their own `Report` class?  I can't without conflating format.  So I'm leaning towards Option B now.  Thoughts?

2021-04-01 00:09 UTC, kbrock commented
> Can you think of a good reason to have users inject their own Report class? I can't without conflating format. So I'm leaning towards Option B now. Thoughts?

There was a request https://github.com/evanphx/benchmark-ips/issues/81 to be able to capture the output. So as long as you could set a string output buffer or something, then that would move this gem towards solving that issue. I had started on a PR to solve that issue but I like where this PR is going and can fix the other PR after you are done here.

2021-04-02 00:25 UTC, nateberkopec commented
Well, I don't have any desire to get rid of `quiet`. I think setting `quiet` should just silently swap out the reporter in the background. So I guess that makes me option B? I don't think the other decisions/points in the PR need to be solved today, maybe we merge reporters/formatters in the future but I don't think that has to be solved now.

2021-04-02 15:42 UTC, allcentury commented
@nateberkopec - thanks for that.  I think this is ready for your review then.

2021-04-02 22:31 UTC, kbrock reviewed
I like all but that one method.
since it is only used in the one spot, this seems a simple change

but obviously, I defer to nick on this all (since he is supporting the gem after all)

2021-04-02 22:31 UTC, kbrock commented on lib/benchmark/ips/job.rb
> +      def set_reporter(quiet:)
I think this is the only part that is suspect.

introducing report= is ok - or not. Just use that and set the value based upon quiet.
but the set_reporter doesn't seem right to me

2021-04-05 14:54 UTC, nateberkopec requested changes

2021-04-05 14:54 UTC, nateberkopec commented on lib/benchmark/ips/job.rb
> +      def set_reporter(quiet:)
@allcentury Purely from a style perspective, `get_` and `set_` methods don't belong in Ruby for me. It looks like PHP or JS. I think this should just be `reporter=`. I have no problem with what the method does.

2021-04-05 14:54 UTC, nateberkopec commented
1 rename and it's GTG

2021-04-05 15:19 UTC, allcentury commented
@nateberkopec perfect, thank you!  I removed the `set` and now `reporter` is a pure function which `quiet=` relies on.

2021-04-05 15:39 UTC, merged

2021-04-05 15:39 UTC, nateberkopec commented
Thank _you_ @allcentury

2021-04-06 23:10 UTC, kbrock commented
thank you @allcentury